### ISSUE TITLE
A custom IMapper cannot be specified when mapping from an attribute

### ISSUE THREAD

**Issue by wapxmas** [edpollitt/Nerdle.AutoConfig#10]
Hi! How I can use mapper for nested fields? E.g.:
interface IA {
 IB property1;
}

interface IB {
someEnum property2;
}

If I am trying like that
```
AutoConfig.WhenMapping<IA>(
mapping =>
                {
                    mapping.Map(x => x.property1.property2).Using<Property2Mapper>();
                });
```
I'll get nothing.

But if I am trying as following
```
AutoConfig.WhenMapping<IB>(
mapping =>
                {
                    mapping.Map(x => x.property2).Using<Property2Mapper>();
                });
```
I'll get exception `....... A custom IMapper cannot be specified when mapping from an attribute`.

Why ?

**Comment by edpollitt** [comment]
Nested property strategies are not supported, so 

`mapping.Map(x => x.property1.property2).Using<Property2Mapper>();`

will not work. I'm planning on fixing this in the future but haven't had free time to work on this project for a while.

Specifying `WhenMapping<IB>` is the correct solution, but the exception indicates that your value needs to be an element, rather than an attribute. I didn't anticipate people using attributes for anything other than simple types, so I didn't add custom mapper support.

Assuming you have some XML something like

`<property1 property2="whatever" />`

you need to change it to

```
<property1> 
    <property2>whatever</property2>
</property1>
```

Let me know if you're still having problems.

**Comment by wapxmas** [comment]
Yes, it does work. Thx.
